// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbs5AzYuktzf5RlcdRqno3CqG5lPjGnPQ',
    appId: '1:413571388536:web:da99d5dab405b6f60f498d',
    messagingSenderId: '413571388536',
    projectId: 'pozdnyakovaprac8',
    authDomain: 'pozdnyakovaprac8.firebaseapp.com',
    storageBucket: 'pozdnyakovaprac8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67MOngZMNZUqzI7LCxHXNQ39kJbYWNV8',
    appId: '1:413571388536:android:a5dfd1860d2fa30f0f498d',
    messagingSenderId: '413571388536',
    projectId: 'pozdnyakovaprac8',
    storageBucket: 'pozdnyakovaprac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5DfllwoWodiiFqgnU6QOuXrWN79xIr_E',
    appId: '1:413571388536:ios:f682f9d71d1638870f498d',
    messagingSenderId: '413571388536',
    projectId: 'pozdnyakovaprac8',
    storageBucket: 'pozdnyakovaprac8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5DfllwoWodiiFqgnU6QOuXrWN79xIr_E',
    appId: '1:413571388536:ios:f682f9d71d1638870f498d',
    messagingSenderId: '413571388536',
    projectId: 'pozdnyakovaprac8',
    storageBucket: 'pozdnyakovaprac8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbs5AzYuktzf5RlcdRqno3CqG5lPjGnPQ',
    appId: '1:413571388536:web:60c310e70a69422a0f498d',
    messagingSenderId: '413571388536',
    projectId: 'pozdnyakovaprac8',
    authDomain: 'pozdnyakovaprac8.firebaseapp.com',
    storageBucket: 'pozdnyakovaprac8.firebasestorage.app',
  );
}
